-- 0113 — Stripe payouts into Wio AED, Jun–Oct 2026 (Owner 2026-10-07: "add the Stripe payouts to the ERP").
-- Wio statements stopped reaching the ERP after 2026-04-27, so STRIPE-202606..202610 showed 0 AED.
-- Source: Stripe payout e-mails (notifications@stripe.com, payout id + arrival date + amount) and, where
-- present, the matching Wio "You've received money" e-mail (sender NETWORK INTERNATIONAL LLC + AEL reference).
-- external_id = Stripe payout id, so a later Wio statement upload of the same deposit is a different key;
-- dedupe on upload by amount+date+contragent before importing that month.
-- Rollback: DELETE FROM bank_transactions WHERE company_bank_account_id='cba_dei_wio_aed' AND external_id LIKE 'po_%' AND source_type='email_inbox';
--           then POST /api/operations/_backfill-dasexperten-com-monthly?from=2026-06&to=2026-10

INSERT OR IGNORE INTO bank_transactions (id, company_bank_account_id, external_id, external_doc_number, direction, status, amount, currency, executed_at, created_at_bank, contragent_name, payment_purpose, raw_payload, created_at, updated_at, source_type, suggested_category_id, suggested_confidence, suggested_reason) VALUES ('bt_stripe_po_1Tam27GyWzlIhMzY7f3yifJQ', 'cba_dei_wio_aed', 'po_1Tam27GyWzlIhMzY7f3yifJQ', 'po_1Tam27GyWzlIhMzY7f3yifJQ', 'incoming', 'Received', 10012, 'AED', 1780315200, 1780315200, 'NETWORK INTERNATIONAL LLC', 'STRIPE payout po_1Tam27GyWzlIhMzY7f3yifJQ', '{"executed_at": "2026-06-01", "direction": "incoming", "amount": 10012, "currency": "AED", "contragent_name": "NETWORK INTERNATIONAL LLC", "payment_purpose": "STRIPE payout po_1Tam27GyWzlIhMzY7f3yifJQ", "external_id": "po_1Tam27GyWzlIhMzY7f3yifJQ", "source": "stripe payout e-mail"}', strftime('%s','now'), strftime('%s','now'), 'email_inbox', 'fc_acquiring_payout', 0.95, 'Stripe payout e-mail');
INSERT OR IGNORE INTO bank_transactions (id, company_bank_account_id, external_id, external_doc_number, direction, status, amount, currency, executed_at, created_at_bank, contragent_name, payment_purpose, raw_payload, created_at, updated_at, source_type, suggested_category_id, suggested_confidence, suggested_reason) VALUES ('bt_stripe_po_1TrSTMGyWzlIhMzYpU09Kv3A', 'cba_dei_wio_aed', 'po_1TrSTMGyWzlIhMzYpU09Kv3A', 'po_1TrSTMGyWzlIhMzYpU09Kv3A', 'incoming', 'Received', 7475, 'AED', 1783944000, 1783944000, 'NETWORK INTERNATIONAL LLC', 'STRIPE payout po_1TrSTMGyWzlIhMzYpU09Kv3A', '{"executed_at": "2026-07-13", "direction": "incoming", "amount": 7475, "currency": "AED", "contragent_name": "NETWORK INTERNATIONAL LLC", "payment_purpose": "STRIPE payout po_1TrSTMGyWzlIhMzYpU09Kv3A", "external_id": "po_1TrSTMGyWzlIhMzYpU09Kv3A", "source": "stripe payout e-mail"}', strftime('%s','now'), strftime('%s','now'), 'email_inbox', 'fc_acquiring_payout', 0.95, 'Stripe payout e-mail');
INSERT OR IGNORE INTO bank_transactions (id, company_bank_account_id, external_id, external_doc_number, direction, status, amount, currency, executed_at, created_at_bank, contragent_name, payment_purpose, raw_payload, created_at, updated_at, source_type, suggested_category_id, suggested_confidence, suggested_reason) VALUES ('bt_stripe_po_1Tz4dGGyWzlIhMzYmiaOSfWn', 'cba_dei_wio_aed', 'po_1Tz4dGGyWzlIhMzYmiaOSfWn', 'po_1Tz4dGGyWzlIhMzYmiaOSfWn', 'incoming', 'Received', 7880, 'AED', 1785758400, 1785758400, 'NETWORK INTERNATIONAL LLC', 'STRIPE payout po_1Tz4dGGyWzlIhMzYmiaOSfWn', '{"executed_at": "2026-08-03", "direction": "incoming", "amount": 7880, "currency": "AED", "contragent_name": "NETWORK INTERNATIONAL LLC", "payment_purpose": "STRIPE payout po_1Tz4dGGyWzlIhMzYmiaOSfWn", "external_id": "po_1Tz4dGGyWzlIhMzYmiaOSfWn", "source": "stripe payout e-mail"}', strftime('%s','now'), strftime('%s','now'), 'email_inbox', 'fc_acquiring_payout', 0.95, 'Stripe payout e-mail');
INSERT OR IGNORE INTO bank_transactions (id, company_bank_account_id, external_id, external_doc_number, direction, status, amount, currency, executed_at, created_at_bank, contragent_name, payment_purpose, raw_payload, created_at, updated_at, source_type, suggested_category_id, suggested_confidence, suggested_reason) VALUES ('bt_stripe_po_1U6gG4GyWzlIhMzYKMocZM70', 'cba_dei_wio_aed', 'po_1U6gG4GyWzlIhMzYKMocZM70', 'po_1U6gG4GyWzlIhMzYKMocZM70', 'incoming', 'Received', 21499, 'AED', 1787572800, 1787572800, 'NETWORK INTERNATIONAL LLC', 'STRIPE payout po_1U6gG4GyWzlIhMzYKMocZM70', '{"executed_at": "2026-08-24", "direction": "incoming", "amount": 21499, "currency": "AED", "contragent_name": "NETWORK INTERNATIONAL LLC", "payment_purpose": "STRIPE payout po_1U6gG4GyWzlIhMzYKMocZM70", "external_id": "po_1U6gG4GyWzlIhMzYKMocZM70", "source": "stripe payout e-mail"}', strftime('%s','now'), strftime('%s','now'), 'email_inbox', 'fc_acquiring_payout', 0.95, 'Stripe payout e-mail');
INSERT OR IGNORE INTO bank_transactions (id, company_bank_account_id, external_id, external_doc_number, direction, status, amount, currency, executed_at, created_at_bank, contragent_name, payment_purpose, raw_payload, created_at, updated_at, source_type, suggested_category_id, suggested_confidence, suggested_reason) VALUES ('bt_stripe_po_1U9DoPGyWzlIhMzY3xRkpLaj', 'cba_dei_wio_aed', 'po_1U9DoPGyWzlIhMzY3xRkpLaj', 'po_1U9DoPGyWzlIhMzY3xRkpLaj', 'incoming', 'Received', 24742, 'AED', 1788177600, 1788177600, 'NETWORK INTERNATIONAL LLC', 'STRIPE payout po_1U9DoPGyWzlIhMzY3xRkpLaj', '{"executed_at": "2026-08-31", "direction": "incoming", "amount": 24742, "currency": "AED", "contragent_name": "NETWORK INTERNATIONAL LLC", "payment_purpose": "STRIPE payout po_1U9DoPGyWzlIhMzY3xRkpLaj", "external_id": "po_1U9DoPGyWzlIhMzY3xRkpLaj", "source": "stripe payout e-mail"}', strftime('%s','now'), strftime('%s','now'), 'email_inbox', 'fc_acquiring_payout', 0.95, 'Stripe payout e-mail');
INSERT OR IGNORE INTO bank_transactions (id, company_bank_account_id, external_id, external_doc_number, direction, status, amount, currency, executed_at, created_at_bank, contragent_name, payment_purpose, raw_payload, created_at, updated_at, source_type, suggested_category_id, suggested_confidence, suggested_reason) VALUES ('bt_stripe_po_1UBlRTGyWzlIhMzYyPwGROcm', 'cba_dei_wio_aed', 'po_1UBlRTGyWzlIhMzYyPwGROcm', 'AEL2609070011730', 'incoming', 'Received', 43887, 'AED', 1788782400, 1788782400, 'NETWORK INTERNATIONAL LLC', 'AEL2609070011730 STRIPE payout po_1UBlRTGyWzlIhMzYyPwGROcm', '{"executed_at": "2026-09-07", "direction": "incoming", "amount": 43887, "currency": "AED", "contragent_name": "NETWORK INTERNATIONAL LLC", "payment_purpose": "AEL2609070011730 STRIPE payout po_1UBlRTGyWzlIhMzYyPwGROcm", "external_id": "po_1UBlRTGyWzlIhMzYyPwGROcm", "source": "stripe payout e-mail + wio receipt e-mail"}', strftime('%s','now'), strftime('%s','now'), 'email_inbox', 'fc_acquiring_payout', 0.95, 'Stripe payout e-mail');
INSERT OR IGNORE INTO bank_transactions (id, company_bank_account_id, external_id, external_doc_number, direction, status, amount, currency, executed_at, created_at_bank, contragent_name, payment_purpose, raw_payload, created_at, updated_at, source_type, suggested_category_id, suggested_confidence, suggested_reason) VALUES ('bt_stripe_po_1UJNCzGyWzlIhMzYGPkKILEA', 'cba_dei_wio_aed', 'po_1UJNCzGyWzlIhMzYGPkKILEA', 'AEL2609280013118000113', 'incoming', 'Received', 33803, 'AED', 1790596800, 1790596800, 'NETWORK INTERNATIONAL LLC', 'AEL2609280013118000113 STRIPE payout po_1UJNCzGyWzlIhMzYGPkKILEA', '{"executed_at": "2026-09-28", "direction": "incoming", "amount": 33803, "currency": "AED", "contragent_name": "NETWORK INTERNATIONAL LLC", "payment_purpose": "AEL2609280013118000113 STRIPE payout po_1UJNCzGyWzlIhMzYGPkKILEA", "external_id": "po_1UJNCzGyWzlIhMzYGPkKILEA", "source": "stripe payout e-mail + wio receipt e-mail"}', strftime('%s','now'), strftime('%s','now'), 'email_inbox', 'fc_acquiring_payout', 0.95, 'Stripe payout e-mail');
INSERT OR IGNORE INTO bank_transactions (id, company_bank_account_id, external_id, external_doc_number, direction, status, amount, currency, executed_at, created_at_bank, contragent_name, payment_purpose, raw_payload, created_at, updated_at, source_type, suggested_category_id, suggested_confidence, suggested_reason) VALUES ('bt_stripe_po_1ULuTDGyWzlIhMzYpfPfL2KU', 'cba_dei_wio_aed', 'po_1ULuTDGyWzlIhMzYpfPfL2KU', 'AEL2610050010350000246', 'incoming', 'Received', 20102, 'AED', 1791201600, 1791201600, 'NETWORK INTERNATIONAL LLC', 'AEL2610050010350000246 STRIPE payout po_1ULuTDGyWzlIhMzYpfPfL2KU', '{"executed_at": "2026-10-05", "direction": "incoming", "amount": 20102, "currency": "AED", "contragent_name": "NETWORK INTERNATIONAL LLC", "payment_purpose": "AEL2610050010350000246 STRIPE payout po_1ULuTDGyWzlIhMzYpfPfL2KU", "external_id": "po_1ULuTDGyWzlIhMzYpfPfL2KU", "source": "stripe payout e-mail + wio receipt e-mail"}', strftime('%s','now'), strftime('%s','now'), 'email_inbox', 'fc_acquiring_payout', 0.95, 'Stripe payout e-mail');
