// =============================================================================
// web/lib/countries.ts — shared country list for partner forms.
// Used by Edit Partner and New Partner pages.
// =============================================================================

export const COUNTRIES: readonly string[] = [
  'Russia',
  'China',
  'Hong Kong',
  'UAE',
  'Vietnam',
  'Armenia',
  'Belarus',
  'Georgia',
  'Kazakhstan',
  'Kyrgyzstan',
  'Moldova',
  'Tajikistan',
  'Turkmenistan',
  'Ukraine',
  'Uzbekistan',
  'Abkhazia',
  'South Ossetia',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belgium',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Brazil',
  'Bulgaria',
  'Burkina Faso',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Chile',
  'Colombia',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Greece',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Japan',
  'Jordan',
  'Kenya',
  'Kuwait',
  'Laos',
  'Latvia',
  'Lebanon',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mexico',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Myanmar',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tanzania',
  'Thailand',
  'Tunisia',
  'Turkey',
  'Uganda',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Venezuela',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];
