/**
 * Operation Attachments — universal document container per operation.
 *
 * Returns a UNIFIED list combining:
 *   - documents (outgoing — generated by us via invoicer)
 *   - operation_attachments (incoming/external — acts, invoices, BL, SWIFT etc.)
 *
 * Owned by main chat. The `documents` table is parallel-chat territory:
 * we only READ from it, never write.
 */
import { Hono } from 'hono';
import type { Env } from '../types';
import { ok, fail } from '../lib/responses';

const attachments = new Hono<{ Bindings: Env }>();

// ─── GET /api/operations/:id/attachments ──────────────────────────────────
// Returns unified list (outgoing from `documents` + incoming from `operation_attachments`)
attachments.get('/api/operations/:id/attachments', async (c) => {
  const operationId = c.req.param('id');

  // Read the operation's status once — used as the "shipment-locked" signal
  // for all attachments below.
  const opRow = await c.env.DB.prepare(
    `SELECT status FROM operations WHERE id = ? AND deleted_at IS NULL`
  ).bind(operationId).first<{ status: string }>();
  const opLocked = opRow && (opRow.status === 'shipped' || opRow.status === 'delivered');

  // Outgoing: documents we generated (parallel chat territory — read only)
  const outgoing = await c.env.DB.prepare(
    `SELECT
       id,
       'outgoing'      AS direction,
       document_type   AS kind,
       document_number AS doc_number,
       document_date   AS doc_date,
       total_amount    AS amount,
       currency,
       NULL            AS issuer,
       pdf_r2_url      AS file_url,
       'invoicer'      AS parsed_from,
       NULL            AS notes,
       created_at,
       CASE WHEN status IN ('sent','final') THEN created_at ELSE NULL END AS sent_at
     FROM documents
     WHERE operation_id = ? AND deleted_at IS NULL
     ORDER BY document_date DESC, created_at DESC`
  ).bind(operationId).all();

  // Incoming: external docs we received and attached
  const incoming = await c.env.DB.prepare(
    `SELECT
       id, direction, kind, doc_number, doc_date,
       amount, currency, issuer, file_url, parsed_from, notes, created_at, sent_at
     FROM operation_attachments
     WHERE operation_id = ? AND deleted_at IS NULL
     ORDER BY doc_date DESC, created_at DESC`
  ).bind(operationId).all();

  const merged = [
    ...(outgoing.results || []),
    ...(incoming.results || []),
  ].sort((a: any, b: any) => {
    const ad = a.doc_date || a.created_at || 0;
    const bd = b.doc_date || b.created_at || 0;
    return bd - ad;
  }).map((row: any) => {
    // Lock signals: own sent_at OR the parent operation has shipped/delivered.
    const lockedBySent = row.sent_at != null;
    const locked = lockedBySent || !!opLocked;
    const lock_reason = !locked ? null
      : lockedBySent ? 'sent'
      : 'op_shipped';
    return { ...row, locked, lock_reason };
  });

  return ok(c, { attachments: merged });
});

// ─── POST /api/operations/:id/attachments ─────────────────────────────────
// Manually attach a document to an operation
attachments.post('/api/operations/:id/attachments', async (c) => {
  const operationId = c.req.param('id');
  const body = await c.req.json();

  const opCheck = await c.env.DB.prepare(
    'SELECT id FROM operations WHERE id = ? AND deleted_at IS NULL'
  ).bind(operationId).first();
  if (!opCheck) {
    return fail(c, 404, [{ code: 'not_found', message: 'Operation not found' }]);
  }

  const direction = body.direction || 'incoming';
  if (direction !== 'incoming' && direction !== 'outgoing') {
    return fail(c, 400, [{ code: 'invalid_direction', message: 'direction must be incoming or outgoing' }]);
  }
  if (!body.kind || typeof body.kind !== 'string') {
    return fail(c, 400, [{ code: 'invalid_kind', message: 'kind is required' }]);
  }

  const id = `att_${crypto.randomUUID()}`;

  // Convert ISO date string to unix if needed
  let docDate: number | null = null;
  if (body.doc_date) {
    if (typeof body.doc_date === 'number') {
      docDate = body.doc_date;
    } else {
      const parsed = Date.parse(body.doc_date);
      if (!isNaN(parsed)) docDate = Math.floor(parsed / 1000);
    }
  }

  await c.env.DB.prepare(
    `INSERT INTO operation_attachments
       (id, operation_id, direction, kind, doc_number, doc_date,
        amount, currency, issuer, file_url, parsed_from, source_ref_id, notes)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
  ).bind(
    id,
    operationId,
    direction,
    body.kind.trim(),
    body.doc_number || null,
    docDate,
    body.amount || null,
    body.currency || null,
    body.issuer || null,
    body.file_url || null,
    body.parsed_from || 'manual',
    body.source_ref_id || null,
    body.notes || null
  ).run();

  const created = await c.env.DB.prepare(
    'SELECT * FROM operation_attachments WHERE id = ?'
  ).bind(id).first();

  return ok(c, { attachment: created });
});

// ─── PATCH /api/attachments/:id ───────────────────────────────────────────
// Update an attachment (incoming only — outgoing is read-only)
attachments.patch('/api/attachments/:id', async (c) => {
  const id = c.req.param('id');
  const body = await c.req.json();

  const existing = await c.env.DB.prepare(
    'SELECT id FROM operation_attachments WHERE id = ? AND deleted_at IS NULL'
  ).bind(id).first();
  if (!existing) {
    return fail(c, 404, [{ code: 'not_found', message: 'Attachment not found' }]);
  }

  const fields: string[] = [];
  const values: any[] = [];
  const allowed = ['kind', 'doc_number', 'doc_date', 'amount', 'currency',
                   'issuer', 'file_url', 'notes', 'direction'];
  for (const f of allowed) {
    if (body[f] !== undefined) {
      let v = body[f];
      if (f === 'doc_date' && v && typeof v !== 'number') {
        const parsed = Date.parse(v);
        v = isNaN(parsed) ? null : Math.floor(parsed / 1000);
      }
      fields.push(`${f} = ?`);
      values.push(v);
    }
  }
  if (fields.length === 0) {
    return fail(c, 400, [{ code: 'no_fields', message: 'No fields to update' }]);
  }
  fields.push('updated_at = unixepoch()');
  values.push(id);

  await c.env.DB.prepare(
    `UPDATE operation_attachments SET ${fields.join(', ')} WHERE id = ?`
  ).bind(...values).run();

  const updated = await c.env.DB.prepare(
    'SELECT * FROM operation_attachments WHERE id = ?'
  ).bind(id).first();

  return ok(c, { attachment: updated });
});

// ─── DELETE /api/attachments/:id ──────────────────────────────────────────
// Server-side lock enforcement: refuse to detach an attachment that:
//   1. has its own sent_at set (already sent outbound), OR
//   2. belongs to an operation in status shipped or delivered.
// Mirrors the UI grey-X rule (cemented 2026-05-29).
attachments.delete('/api/attachments/:id', async (c) => {
  const id = c.req.param('id');
  const existing = await c.env.DB.prepare(
    `SELECT a.id, a.sent_at, o.status AS op_status
       FROM operation_attachments a
       LEFT JOIN operations o ON o.id = a.operation_id
      WHERE a.id = ? AND a.deleted_at IS NULL`
  ).bind(id).first<{ id: string; sent_at: number | null; op_status: string | null }>();
  if (!existing) {
    return fail(c, 404, [{ code: 'not_found', message: 'Attachment not found' }]);
  }
  if (existing.sent_at) {
    return fail(c, 409, [{ code: 'attachment_locked', message: 'Document was sent outbound and cannot be detached.' }]);
  }
  if (existing.op_status === 'shipped' || existing.op_status === 'delivered') {
    return fail(c, 409, [{ code: 'attachment_locked', message: 'Operation has shipped/been delivered — documents are locked.' }]);
  }
  await c.env.DB.prepare(
    'UPDATE operation_attachments SET deleted_at = unixepoch() WHERE id = ?'
  ).bind(id).run();
  return ok(c, { id, deleted: true });
});

// ─── GET /api/attachments/kinds ──────────────────────────────────────────
// Returns distinct kinds used so far (for autocomplete dropdown in UI)
attachments.get('/api/attachments/kinds', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT DISTINCT kind FROM operation_attachments
     WHERE deleted_at IS NULL AND kind IS NOT NULL
     UNION
     SELECT DISTINCT document_type AS kind FROM documents
     WHERE deleted_at IS NULL AND document_type IS NOT NULL
     ORDER BY kind`
  ).all();
  const kinds = (rows.results || []).map((r: any) => r.kind);
  return ok(c, { kinds });
});

export default attachments;
